[#packaging_types]
= Packaging Types (Uberjars & Hollow Jars)

When using WildFly Swarm, you have two different ways to package your runtime and application, depending on how you intend to use and deploy it:

## Uberjar

An _uberjar_ is a single Java `.jar` file that includes everything that is required to execute your application.
This means both the runtime components you select--the parts you may consider to be the app server--along with the application components (your `.war` file).

An uberjar is useful in many continuous integration and continuous deployment (CI/CD) pipeline styles, in which a single executable binary artifact is produced and moved through testing, validation, and production environments in your organization.

The name of the uberjars that WildFly Swarm produces includes the name of your application and the `-swarm.jar` suffix.

An uberjar can be executed like any executable JAR:

[source]
----
$ java -jar myapp-swarm.jar
----

## Hollow JAR

A _hollow JAR_ is similar to the uberjar above, but includes only the runtime components, not your application code.

A hollow JAR works well for deployment processes that involve Linux containers such as Docker.
When using containers, place the runtime components in a container image lower in the hierarchy--because it changes less often--so the higher layer that contains only your application code can be rebuilt more quickly.

The name of the hollow JARS that WildFly Swarm produces includes the name of your application along with the suffix `-hollowswarm.jar`.

To execute your application, you must provide the `.war` file with it as an argument on the command-line when executing the hollow JAR:

[source]
----
$ java -jar myapp-hollowswarm.jar myapp.war
----

