
[id='creating-a-datasource_{context}']
= Creating a datasource

:parent-context: {context}

When working with Java applications, a _datasource_ has the following components, both equally important:

* The JDBC driver
* The datasource definition

The task of the JDBC driver is communicating with the database while providing a constant API to application developers.
An application must supply its own JDBC driver because of the wide range of available databases and the driver version.
Usually, the application does not directly interact with the JDBC driver; instead, the underlying runtime manages creating a datasource, which provides an efficient way to share and manage a discrete connection or a pool of connections to a particular database using the driver.

== Configuring a JDBC driver

These are the options how to configure JDBC drivers:

include::../modules/proc_auto-detecting-jdbc-drivers.adoc[leveloffset=+2]

include::../modules/proc_configuring-the-jdbc-driver-manually.adoc[leveloffset=+2]

include::../modules/proc_configuring-a-datasource.adoc[leveloffset=+1]

include::../modules/ref_example-yaml-configuration-with-a-h2-datasource.adoc[leveloffset=+1]

:context: {parent-context}

